version: '3'
services:
  react-app:
    build:
      context: ./react-app
    ports:
      - "3000:3000" # Map the React app server port
    environment:
      - PUBLIC_URL=http://localhost:3000
    volumes:
      - ./react-app:/app # Mount the app code (local:container)
  poc-api:
    build:
      context: ./api
    ports:
      - "3001:3001" # Map the API (JSON server) port
    volumes:
      - ./api:/app # Mount the app code (local:container)